workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      cancel_previous_builds: true
      branch_patterns:
        - pattern: 'main'
          include: true
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "site.tunckankilic.vitalsync"
      flutter: stable
      xcode: latest
      cocoapods: default
    integrations:
      app_store_connect: Code Magic CI/CD
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up signing
        script: |
          keychain add-certificates
          xcode-project use-profiles
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install --repo-update
      - name: Run analyze
        script: |
          flutter analyze --no-fatal-infos
        ignore_failure: true
      - name: Run tests
        script: |
          flutter test test/data/repositories/
        ignore_failure: true
      - name: Increment build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" 2>/dev/null || true)
          if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" = "0" ]; then
            LATEST_BUILD=1
          fi
          NEW_BUILD=$((LATEST_BUILD + 1))
          echo "BUILD_NUMBER=$NEW_BUILD" >> $CM_ENV
          echo "Latest build: $LATEST_BUILD -> New build: $NEW_BUILD"
      - name: Build iOS
        script: |
          flutter build ipa \
            --release \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - tuncsoftwarehere@gmail.com
        notify:
          success: true
          failure: true

  ios-debug:
    name: iOS Debug Build (PR Check)
    max_build_duration: 30
    instance_type: mac_mini_m2
    triggering:
      events:
        - pull_request
      cancel_previous_builds: true
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
        - pattern: 'Day-*'
          include: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run analyze
        script: |
          flutter analyze --no-fatal-infos
        ignore_failure: true
      - name: Run tests
        script: |
          flutter test
        ignore_failure: true
