/// VitalSync — Add Exercise Dialog
///
/// Dialog/Sheet for creating custom exercises.
library;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:vitalsync/core/enums/equipment.dart';
import 'package:vitalsync/core/enums/exercise_category.dart';
import 'package:vitalsync/core/l10n/app_localizations.dart';
import 'package:vitalsync/domain/entities/fitness/exercise.dart';

import '../providers/exercise_provider.dart';

/// Dialog to add a custom exercise.
class AddExerciseDialog extends ConsumerStatefulWidget {
  /// Creates an add exercise dialog.
  const AddExerciseDialog({super.key});

  @override
  ConsumerState<AddExerciseDialog> createState() => _AddExerciseDialogState();
}

class _AddExerciseDialogState extends ConsumerState<AddExerciseDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _instructionsController = TextEditingController();
  late final TextEditingController _muscleGroupController;

  // Default values
  ExerciseCategory _selectedCategory = ExerciseCategory.chest;
  Equipment _selectedEquipment = Equipment.barbell;

  @override
  void initState() {
    super.initState();
    _muscleGroupController = TextEditingController(
      text: _selectedCategory.displayName,
    );
  }

  @override
  void dispose() {
    _nameController.dispose();
    _instructionsController.dispose();
    _muscleGroupController.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;

    final exercise = Exercise(
      id: 0, // ID generated by DB
      name: _nameController.text.trim(),
      category: _selectedCategory,
      muscleGroup: _muscleGroupController.text.trim(),
      equipment: _selectedEquipment,
      instructions: _instructionsController.text.trim(),
      isCustom: true,
      createdAt: DateTime.now(),
    );

    try {
      await ref.read(exerciseProvider.notifier).addCustomExercise(exercise);
      if (mounted) {
        context.pop();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(AppLocalizations.of(context).exerciseAdded)),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error adding exercise: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    final theme = Theme.of(context);

    return Dialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      child: Container(
        padding: const EdgeInsets.all(24),
        constraints: const BoxConstraints(maxWidth: 400),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Text(
                  l10n.createCustomExercise,
                  style: theme.textTheme.headlineSmall?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 24),

                // Name Field
                TextFormField(
                  controller: _nameController,
                  decoration: InputDecoration(
                    labelText: l10n.exerciseName,
                    border: const OutlineInputBorder(),
                    filled: true,
                    fillColor: theme.colorScheme.surfaceContainerHighest
                        .withValues(alpha: 0.3),
                  ),
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return l10n.requiredField;
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),

                // Category Dropdown
                DropdownButtonFormField<ExerciseCategory>(
                  initialValue: _selectedCategory,
                  decoration: InputDecoration(
                    labelText: l10n.fitnessCategory,
                    border: const OutlineInputBorder(),
                  ),
                  items: ExerciseCategory.values.map((category) {
                    return DropdownMenuItem(
                      value: category,
                      child: Text(category.displayName),
                    );
                  }).toList(),
                  onChanged: (value) {
                    if (value != null) {
                      setState(() {
                        _selectedCategory = value;
                        // Update muscle group to match category default
                        _muscleGroupController.text = value.displayName;
                      });
                    }
                  },
                ),
                const SizedBox(height: 16),

                // Muscle Group
                TextFormField(
                  controller: _muscleGroupController,
                  decoration: InputDecoration(
                    labelText: l10n.muscleGroup,
                    border: const OutlineInputBorder(),
                  ),
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return l10n.requiredField;
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),

                // Equipment Dropdown
                DropdownButtonFormField<Equipment>(
                  initialValue: _selectedEquipment,
                  decoration: InputDecoration(
                    labelText: l10n.equipment,
                    border: const OutlineInputBorder(),
                  ),
                  items: Equipment.values.map((equipment) {
                    return DropdownMenuItem(
                      value: equipment,
                      child: Text(equipment.displayName),
                    );
                  }).toList(),
                  onChanged: (value) {
                    if (value != null) {
                      setState(() {
                        _selectedEquipment = value;
                      });
                    }
                  },
                ),
                const SizedBox(height: 16),

                // Instructions Field
                TextFormField(
                  controller: _instructionsController,
                  decoration: InputDecoration(
                    labelText: l10n.instructions,
                    border: const OutlineInputBorder(),
                    filled: true,
                    fillColor: theme.colorScheme.surfaceContainerHighest
                        .withValues(alpha: 0.3),
                  ),
                  maxLines: 3,
                ),
                const SizedBox(height: 24),

                // Actions
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    TextButton(
                      onPressed: () => context.pop(),
                      child: Text(l10n.cancel),
                    ),
                    const SizedBox(width: 8),
                    FilledButton(onPressed: _save, child: Text(l10n.save)),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
