/// VitalSync — Generated Insights Table (Insights Module).
library;

import 'package:drift/drift.dart';

import '../../../../core/enums/insight_category.dart';
import '../../../../core/enums/insight_priority.dart';
import '../../../../core/enums/insight_type.dart';

/// Generated insights table for storing rule-based insights.
///
/// Insights are generated by the InsightEngine based on health and fitness data.
/// They can be correlations, trends, anomalies, suggestions, or milestones.
/// Insights have validity periods and can be marked as read or dismissed.
@DataClassName('GeneratedInsightData')
class GeneratedInsights extends Table {
  /// Primary key.
  IntColumn get id => integer().autoIncrement()();

  /// Type of insight (correlation, trend, anomaly, suggestion, milestone).
  /// Stored as string, converted to/from InsightType enum.
  TextColumn get insightType => textEnum<InsightType>()();

  /// Category of insight (health, fitness, crossModule).
  /// Stored as string, converted to/from InsightCategory enum.
  TextColumn get category => textEnum<InsightCategory>()();

  /// Insight title (short, user-facing).
  /// Example: "Workout Performance Improving", "Medication Adherence Pattern"
  TextColumn get title => text()();

  /// Insight message (detailed explanation).
  /// Example: "Your squat 1RM has increased by 15% over the past month"
  TextColumn get message => text()();

  /// JSON data backing this insight.
  /// Contains the raw data used to generate the insight.
  /// Example: {"exercise": "Squat", "oldPR": 100, "newPR": 115, "timeFrame": "30days"}
  TextColumn get data => text()();

  /// Priority level (1-5) for display ordering.
  /// 5 = highest priority (show first), 1 = lowest priority
  IntColumn get priority => intEnum<InsightPriority>()();

  /// Whether the user has read this insight.
  BoolColumn get isRead => boolean().withDefault(const Constant(false))();

  /// Whether the user has dismissed this insight.
  /// Dismissed insights are hidden from the UI.
  BoolColumn get isDismissed => boolean().withDefault(const Constant(false))();

  /// When this insight expires and should be removed.
  /// Insights are time-sensitive and become irrelevant after a period.
  DateTimeColumn get validUntil => dateTime()();

  /// When this insight was generated by the InsightEngine.
  DateTimeColumn get generatedAt =>
      dateTime().withDefault(currentDateAndTime)();
}
