import '../../../core/enums/trend_direction.dart';
import '../fitness/personal_record.dart';
import 'insight.dart';

/// Comprehensive weekly report combining health, fitness, and cross-module data.
///
/// Generated by [WeeklyReportService] for a specific week, this report provides:
/// 1. Health Summary: Medication compliance, trends, symptom data, and
///    descriptive meal / glucose counts
/// 2. Fitness Summary: Workout stats, volume, PRs, and streaks
/// 3. Cross-Module Highlights: Health score, best day, top insights
/// 4. Next Week Suggestions: Actionable recommendations
class WeeklyReport {
  const WeeklyReport({
    required this.startDate,
    required this.endDate,
    required this.generatedAt,
    // Health Summary
    required this.medicationCompliance,
    required this.complianceTrendVsPrevious,
    required this.missedMedicationsCount,
    this.mostProblematicTimeSlot,
    required this.symptomsLoggedCount,
    this.mostFrequentSymptom,
    // Dose outcome breakdown and previous-week figures. Default to zero so a
    // report built before these existed - or restored from an older export -
    // still constructs.
    this.takenMedicationsCount = 0,
    this.skippedMedicationsCount = 0,
    this.previousMedicationCompliance = 0,
    this.previousSymptomsLoggedCount = 0,
    // Measurement counts. Default to zero so a report built before these
    // existed - or restored from an older export - still constructs.
    this.mealsLoggedCount = 0,
    this.glucoseReadingsCount = 0,
    this.mealsWithCoverageCount = 0,
    // Fitness Summary
    required this.workoutCount,
    required this.totalVolume,
    required this.volumeTrendVsPrevious,
    required this.totalWorkoutDuration,
    required this.newPRs,
    required this.currentStreak,
    this.dailyVolumes = const [],
    this.previousDailyVolumes = const [],
    this.previousWorkoutCount = 0,
    this.bestWorkoutName,
    this.bestWorkoutVolume,
    this.exerciseNames = const {},
    // Cross-Module Highlights
    this.bestDay,
    required this.healthScore,
    required this.topInsights,
    // Next Week Suggestions
    required this.suggestions,
  });

  /// Creates a WeeklyReport from JSON.
  factory WeeklyReport.fromJson(Map<String, dynamic> json) {
    final healthSummary = json['health_summary'] as Map<String, dynamic>;
    final fitnessSummary = json['fitness_summary'] as Map<String, dynamic>;
    final crossModule = json['cross_module_highlights'] as Map<String, dynamic>;

    return WeeklyReport(
      startDate: DateTime.parse(json['start_date'] as String),
      endDate: DateTime.parse(json['end_date'] as String),
      generatedAt: DateTime.parse(json['generated_at'] as String),
      medicationCompliance: healthSummary['medication_compliance'] as double,
      complianceTrendVsPrevious: TrendDirection.values.firstWhere(
        (e) => e.name == healthSummary['compliance_trend'],
      ),
      missedMedicationsCount: healthSummary['missed_medications_count'] as int,
      mostProblematicTimeSlot:
          healthSummary['most_problematic_time_slot'] as String?,
      symptomsLoggedCount: healthSummary['symptoms_logged_count'] as int,
      mostFrequentSymptom: healthSummary['most_frequent_symptom'] as String?,
      takenMedicationsCount:
          healthSummary['taken_medications_count'] as int? ?? 0,
      skippedMedicationsCount:
          healthSummary['skipped_medications_count'] as int? ?? 0,
      previousMedicationCompliance:
          (healthSummary['previous_medication_compliance'] as num?)
                  ?.toDouble() ??
              0,
      previousSymptomsLoggedCount:
          healthSummary['previous_symptoms_logged_count'] as int? ?? 0,
      mealsLoggedCount: healthSummary['meals_logged_count'] as int? ?? 0,
      glucoseReadingsCount:
          healthSummary['glucose_readings_count'] as int? ?? 0,
      mealsWithCoverageCount:
          healthSummary['meals_with_coverage_count'] as int? ?? 0,
      workoutCount: fitnessSummary['workout_count'] as int,
      totalVolume: fitnessSummary['total_volume_kg'] as double,
      volumeTrendVsPrevious: TrendDirection.values.firstWhere(
        (e) => e.name == fitnessSummary['volume_trend'],
      ),
      totalWorkoutDuration:
          fitnessSummary['total_workout_duration_minutes'] as int,
      newPRs: (fitnessSummary['new_prs'] as List)
          .map(
            (pr) => PersonalRecord(
              id: 0, // Not persisted from JSON
              exerciseId: pr['exercise_id'] as int,
              weight: pr['weight'] as double,
              reps: pr['reps'] as int,
              estimated1RM: pr['estimated_1rm'] as double,
              achievedAt: DateTime.parse(pr['achieved_at'] as String),
            ),
          )
          .toList(),
      currentStreak: fitnessSummary['current_streak'] as int,
      dailyVolumes:
          (fitnessSummary['daily_volumes'] as List?)
              ?.map((v) => (v as num).toDouble())
              .toList() ??
          const [],
      previousDailyVolumes:
          (fitnessSummary['previous_daily_volumes'] as List?)
              ?.map((v) => (v as num).toDouble())
              .toList() ??
          const [],
      previousWorkoutCount:
          fitnessSummary['previous_workout_count'] as int? ?? 0,
      bestWorkoutName:
          (fitnessSummary['best_workout'] as Map<String, dynamic>?)?['name']
              as String?,
      bestWorkoutVolume:
          ((fitnessSummary['best_workout']
                  as Map<String, dynamic>?)?['volume_kg'] as num?)
              ?.toDouble(),
      exerciseNames: {
        for (final pr in (fitnessSummary['new_prs'] as List))
          if ((pr as Map<String, dynamic>)['exercise_name'] != null)
            pr['exercise_id'] as int: pr['exercise_name'] as String,
      },
      bestDay: crossModule['best_day'] != null
          ? DateTime.parse(crossModule['best_day'] as String)
          : null,
      healthScore: crossModule['health_score'] as double,
      topInsights: [], // Insights not fully serialized in JSON
      suggestions: (json['next_week_suggestions'] as List).cast<String>(),
    );
  }

  // ── Core Metadata ──────────────────────────────────────────────────
  final DateTime startDate;
  final DateTime endDate;
  final DateTime generatedAt;

  // ── Health Summary ─────────────────────────────────────────────────
  final double medicationCompliance; // 0.0 to 1.0
  final TrendDirection complianceTrendVsPrevious;

  /// Doses logged as missed. Strictly [MedicationLogStatus.missed] — skipped
  /// and still-pending doses are counted in their own fields, so the four
  /// outcomes partition the week's logs.
  final int missedMedicationsCount;
  final String? mostProblematicTimeSlot; // "morning", "afternoon", "evening"
  final int symptomsLoggedCount;
  final String? mostFrequentSymptom;

  /// Doses logged as taken.
  final int takenMedicationsCount;

  /// Doses the user deliberately skipped, as opposed to missed.
  final int skippedMedicationsCount;

  /// Previous week's compliance, kept so the report can state the change
  /// without the reader having to fetch a second report.
  final double previousMedicationCompliance;

  /// Previous week's symptom count, for the same reason.
  final int previousSymptomsLoggedCount;

  /// How many meals were logged in the week. A count, not an assessment —
  /// nothing here says anything about what was eaten.
  final int mealsLoggedCount;

  /// How many glucose measurements were recorded in the week, from any
  /// source. A count only: no average, no range, no trend.
  final int glucoseReadingsCount;

  /// How many of [mealsLoggedCount] had enough measurement data around them,
  /// per `MealDataCoverageService`. A data-completeness tally — it says
  /// nothing about the meals or the readings.
  final int mealsWithCoverageCount;

  // ── Fitness Summary ────────────────────────────────────────────────
  final int workoutCount;
  final double totalVolume; // kg
  final TrendDirection volumeTrendVsPrevious;
  final int totalWorkoutDuration; // minutes
  final List<PersonalRecord> newPRs;
  final int currentStreak;

  /// Volume per weekday, Monday first — seven entries, zero on rest days.
  /// Empty only on a report built before this field existed.
  final List<double> dailyVolumes;

  /// The same series for the previous week, drawn as ghost bars.
  final List<double> previousDailyVolumes;

  /// Previous week's session count, for the comparison rings.
  final int previousWorkoutCount;

  /// Name and volume of the week's heaviest session, null when the week had
  /// no sessions.
  final String? bestWorkoutName;
  final double? bestWorkoutVolume;

  /// Exercise id → name, covering every exercise in [newPRs]. [PersonalRecord]
  /// carries only the id, and the report is rendered without database access.
  final Map<int, String> exerciseNames;

  // ── Cross-Module Highlights ────────────────────────────────────────
  final DateTime? bestDay; // Day with both compliance + workout
  final double healthScore; // 0-100
  final List<Insight> topInsights; // Top 3 insights

  // ── Next Week Suggestions ──────────────────────────────────────────
  final List<String> suggestions;

  WeeklyReport copyWith({
    DateTime? startDate,
    DateTime? endDate,
    DateTime? generatedAt,
    double? medicationCompliance,
    TrendDirection? complianceTrendVsPrevious,
    int? missedMedicationsCount,
    String? mostProblematicTimeSlot,
    int? symptomsLoggedCount,
    String? mostFrequentSymptom,
    int? takenMedicationsCount,
    int? skippedMedicationsCount,
    double? previousMedicationCompliance,
    int? previousSymptomsLoggedCount,
    int? mealsLoggedCount,
    int? glucoseReadingsCount,
    int? mealsWithCoverageCount,
    int? workoutCount,
    double? totalVolume,
    TrendDirection? volumeTrendVsPrevious,
    int? totalWorkoutDuration,
    List<PersonalRecord>? newPRs,
    int? currentStreak,
    List<double>? dailyVolumes,
    List<double>? previousDailyVolumes,
    int? previousWorkoutCount,
    String? bestWorkoutName,
    double? bestWorkoutVolume,
    Map<int, String>? exerciseNames,
    DateTime? bestDay,
    double? healthScore,
    List<Insight>? topInsights,
    List<String>? suggestions,
  }) {
    return WeeklyReport(
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      generatedAt: generatedAt ?? this.generatedAt,
      medicationCompliance: medicationCompliance ?? this.medicationCompliance,
      complianceTrendVsPrevious:
          complianceTrendVsPrevious ?? this.complianceTrendVsPrevious,
      missedMedicationsCount:
          missedMedicationsCount ?? this.missedMedicationsCount,
      mostProblematicTimeSlot:
          mostProblematicTimeSlot ?? this.mostProblematicTimeSlot,
      symptomsLoggedCount: symptomsLoggedCount ?? this.symptomsLoggedCount,
      mostFrequentSymptom: mostFrequentSymptom ?? this.mostFrequentSymptom,
      takenMedicationsCount:
          takenMedicationsCount ?? this.takenMedicationsCount,
      skippedMedicationsCount:
          skippedMedicationsCount ?? this.skippedMedicationsCount,
      previousMedicationCompliance:
          previousMedicationCompliance ?? this.previousMedicationCompliance,
      previousSymptomsLoggedCount:
          previousSymptomsLoggedCount ?? this.previousSymptomsLoggedCount,
      mealsLoggedCount: mealsLoggedCount ?? this.mealsLoggedCount,
      glucoseReadingsCount: glucoseReadingsCount ?? this.glucoseReadingsCount,
      mealsWithCoverageCount:
          mealsWithCoverageCount ?? this.mealsWithCoverageCount,
      workoutCount: workoutCount ?? this.workoutCount,
      totalVolume: totalVolume ?? this.totalVolume,
      volumeTrendVsPrevious:
          volumeTrendVsPrevious ?? this.volumeTrendVsPrevious,
      totalWorkoutDuration: totalWorkoutDuration ?? this.totalWorkoutDuration,
      newPRs: newPRs ?? this.newPRs,
      currentStreak: currentStreak ?? this.currentStreak,
      dailyVolumes: dailyVolumes ?? this.dailyVolumes,
      previousDailyVolumes: previousDailyVolumes ?? this.previousDailyVolumes,
      previousWorkoutCount: previousWorkoutCount ?? this.previousWorkoutCount,
      bestWorkoutName: bestWorkoutName ?? this.bestWorkoutName,
      bestWorkoutVolume: bestWorkoutVolume ?? this.bestWorkoutVolume,
      exerciseNames: exerciseNames ?? this.exerciseNames,
      bestDay: bestDay ?? this.bestDay,
      healthScore: healthScore ?? this.healthScore,
      topInsights: topInsights ?? this.topInsights,
      suggestions: suggestions ?? this.suggestions,
    );
  }

  /// Converts the weekly report to JSON for GDPR data export.
  Map<String, dynamic> toJson() {
    return {
      'start_date': startDate.toIso8601String(),
      'end_date': endDate.toIso8601String(),
      'generated_at': generatedAt.toIso8601String(),
      'health_summary': {
        'medication_compliance': medicationCompliance,
        'compliance_trend': complianceTrendVsPrevious.name,
        'missed_medications_count': missedMedicationsCount,
        'taken_medications_count': takenMedicationsCount,
        'skipped_medications_count': skippedMedicationsCount,
        'previous_medication_compliance': previousMedicationCompliance,
        'previous_symptoms_logged_count': previousSymptomsLoggedCount,
        'most_problematic_time_slot': mostProblematicTimeSlot,
        'symptoms_logged_count': symptomsLoggedCount,
        'most_frequent_symptom': mostFrequentSymptom,
        'meals_logged_count': mealsLoggedCount,
        'glucose_readings_count': glucoseReadingsCount,
        'meals_with_coverage_count': mealsWithCoverageCount,
      },
      'fitness_summary': {
        'workout_count': workoutCount,
        'total_volume_kg': totalVolume,
        'volume_trend': volumeTrendVsPrevious.name,
        'total_workout_duration_minutes': totalWorkoutDuration,
        'daily_volumes': dailyVolumes,
        'previous_daily_volumes': previousDailyVolumes,
        'previous_workout_count': previousWorkoutCount,
        'best_workout': bestWorkoutName == null
            ? null
            : {'name': bestWorkoutName, 'volume_kg': bestWorkoutVolume},
        'new_prs': newPRs
            .map(
              (pr) => {
                'exercise_id': pr.exerciseId,
                // Resolved name, so the report renders without touching the
                // database. Null when the exercise no longer exists.
                'exercise_name': exerciseNames[pr.exerciseId],
                'weight': pr.weight,
                'reps': pr.reps,
                'estimated_1rm': pr.estimated1RM,
                'achieved_at': pr.achievedAt.toIso8601String(),
              },
            )
            .toList(),
        'current_streak': currentStreak,
      },
      'cross_module_highlights': {
        'best_day': bestDay?.toIso8601String(),
        'health_score': healthScore,
        'top_insights': topInsights
            .map(
              (i) => {
                'title': i.title,
                'message': i.message,
                'category': i.category.name,
                'priority': i.priority.name,
              },
            )
            .toList(),
      },
      'next_week_suggestions': suggestions,
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is WeeklyReport &&
        other.startDate == startDate &&
        other.endDate == endDate &&
        other.generatedAt == generatedAt &&
        other.medicationCompliance == medicationCompliance &&
        other.complianceTrendVsPrevious == complianceTrendVsPrevious &&
        other.missedMedicationsCount == missedMedicationsCount &&
        other.mostProblematicTimeSlot == mostProblematicTimeSlot &&
        other.symptomsLoggedCount == symptomsLoggedCount &&
        other.mostFrequentSymptom == mostFrequentSymptom &&
        other.takenMedicationsCount == takenMedicationsCount &&
        other.skippedMedicationsCount == skippedMedicationsCount &&
        other.previousMedicationCompliance == previousMedicationCompliance &&
        other.previousSymptomsLoggedCount == previousSymptomsLoggedCount &&
        other.mealsLoggedCount == mealsLoggedCount &&
        other.glucoseReadingsCount == glucoseReadingsCount &&
        other.mealsWithCoverageCount == mealsWithCoverageCount &&
        other.workoutCount == workoutCount &&
        other.totalVolume == totalVolume &&
        other.volumeTrendVsPrevious == volumeTrendVsPrevious &&
        other.totalWorkoutDuration == totalWorkoutDuration &&
        _listEquals(other.newPRs, newPRs) &&
        other.currentStreak == currentStreak &&
        _listEquals(other.dailyVolumes, dailyVolumes) &&
        _listEquals(other.previousDailyVolumes, previousDailyVolumes) &&
        other.previousWorkoutCount == previousWorkoutCount &&
        other.bestWorkoutName == bestWorkoutName &&
        other.bestWorkoutVolume == bestWorkoutVolume &&
        _mapEquals(other.exerciseNames, exerciseNames) &&
        other.bestDay == bestDay &&
        other.healthScore == healthScore &&
        _listEquals(other.topInsights, topInsights) &&
        _listEquals(other.suggestions, suggestions);
  }

  /// Element-wise list comparison.
  ///
  /// The three list fields used to be compared by length alone, which made
  /// two reports with entirely different PRs, insights or suggestions come
  /// out equal.
  static bool _listEquals<T>(List<T> a, List<T> b) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }

  /// Entry-wise map comparison.
  static bool _mapEquals<K, V>(Map<K, V> a, Map<K, V> b) {
    if (a.length != b.length) return false;
    for (final entry in a.entries) {
      if (!b.containsKey(entry.key) || b[entry.key] != entry.value) {
        return false;
      }
    }
    return true;
  }

  /// Hashes the list fields by their contents, matching [operator ==].
  /// `List.hashCode` is identity-based, so hashing those directly would let
  /// two equal reports carry different hashes.
  @override
  int get hashCode {
    return startDate.hashCode ^
        endDate.hashCode ^
        generatedAt.hashCode ^
        medicationCompliance.hashCode ^
        complianceTrendVsPrevious.hashCode ^
        missedMedicationsCount.hashCode ^
        mostProblematicTimeSlot.hashCode ^
        symptomsLoggedCount.hashCode ^
        mostFrequentSymptom.hashCode ^
        takenMedicationsCount.hashCode ^
        skippedMedicationsCount.hashCode ^
        previousMedicationCompliance.hashCode ^
        previousSymptomsLoggedCount.hashCode ^
        mealsLoggedCount.hashCode ^
        glucoseReadingsCount.hashCode ^
        mealsWithCoverageCount.hashCode ^
        workoutCount.hashCode ^
        totalVolume.hashCode ^
        volumeTrendVsPrevious.hashCode ^
        totalWorkoutDuration.hashCode ^
        Object.hashAll(newPRs) ^
        currentStreak.hashCode ^
        Object.hashAll(dailyVolumes) ^
        Object.hashAll(previousDailyVolumes) ^
        previousWorkoutCount.hashCode ^
        bestWorkoutName.hashCode ^
        bestWorkoutVolume.hashCode ^
        Object.hashAllUnordered(
          exerciseNames.entries.map((e) => Object.hash(e.key, e.value)),
        ) ^
        bestDay.hashCode ^
        healthScore.hashCode ^
        Object.hashAll(topInsights) ^
        Object.hashAll(suggestions);
  }

  @override
  String toString() {
    return 'WeeklyReport(startDate: $startDate, endDate: $endDate, '
        'medicationCompliance: $medicationCompliance, '
        'workoutCount: $workoutCount, healthScore: $healthScore)';
  }
}
