import '../../../core/enums/trend_direction.dart';
import '../fitness/personal_record.dart';
import 'insight.dart';

/// Comprehensive weekly report combining health, fitness, and cross-module data.
///
/// Generated by [WeeklyReportService] for a specific week, this report provides:
/// 1. Health Summary: Medication compliance, trends, and symptom data
/// 2. Fitness Summary: Workout stats, volume, PRs, and streaks
/// 3. Cross-Module Highlights: Health score, best day, top insights
/// 4. Next Week Suggestions: Actionable recommendations
class WeeklyReport {
  const WeeklyReport({
    required this.startDate,
    required this.endDate,
    required this.generatedAt,
    // Health Summary
    required this.medicationCompliance,
    required this.complianceTrendVsPrevious,
    required this.missedMedicationsCount,
    this.mostProblematicTimeSlot,
    required this.symptomsLoggedCount,
    this.mostFrequentSymptom,
    // Fitness Summary
    required this.workoutCount,
    required this.totalVolume,
    required this.volumeTrendVsPrevious,
    required this.totalWorkoutDuration,
    required this.newPRs,
    required this.currentStreak,
    // Cross-Module Highlights
    this.bestDay,
    required this.healthScore,
    required this.topInsights,
    // Next Week Suggestions
    required this.suggestions,
  });

  /// Creates a WeeklyReport from JSON.
  factory WeeklyReport.fromJson(Map<String, dynamic> json) {
    final healthSummary = json['health_summary'] as Map<String, dynamic>;
    final fitnessSummary = json['fitness_summary'] as Map<String, dynamic>;
    final crossModule = json['cross_module_highlights'] as Map<String, dynamic>;

    return WeeklyReport(
      startDate: DateTime.parse(json['start_date'] as String),
      endDate: DateTime.parse(json['end_date'] as String),
      generatedAt: DateTime.parse(json['generated_at'] as String),
      medicationCompliance: healthSummary['medication_compliance'] as double,
      complianceTrendVsPrevious: TrendDirection.values.firstWhere(
        (e) => e.name == healthSummary['compliance_trend'],
      ),
      missedMedicationsCount: healthSummary['missed_medications_count'] as int,
      mostProblematicTimeSlot:
          healthSummary['most_problematic_time_slot'] as String?,
      symptomsLoggedCount: healthSummary['symptoms_logged_count'] as int,
      mostFrequentSymptom: healthSummary['most_frequent_symptom'] as String?,
      workoutCount: fitnessSummary['workout_count'] as int,
      totalVolume: fitnessSummary['total_volume_kg'] as double,
      volumeTrendVsPrevious: TrendDirection.values.firstWhere(
        (e) => e.name == fitnessSummary['volume_trend'],
      ),
      totalWorkoutDuration:
          fitnessSummary['total_workout_duration_minutes'] as int,
      newPRs: (fitnessSummary['new_prs'] as List)
          .map(
            (pr) => PersonalRecord(
              id: 0, // Not persisted from JSON
              exerciseId: pr['exercise_id'] as int,
              weight: pr['weight'] as double,
              reps: pr['reps'] as int,
              estimated1RM: pr['estimated_1rm'] as double,
              achievedAt: DateTime.parse(pr['achieved_at'] as String),
            ),
          )
          .toList(),
      currentStreak: fitnessSummary['current_streak'] as int,
      bestDay: crossModule['best_day'] != null
          ? DateTime.parse(crossModule['best_day'] as String)
          : null,
      healthScore: crossModule['health_score'] as double,
      topInsights: [], // Insights not fully serialized in JSON
      suggestions: (json['next_week_suggestions'] as List).cast<String>(),
    );
  }

  // ── Core Metadata ──────────────────────────────────────────────────
  final DateTime startDate;
  final DateTime endDate;
  final DateTime generatedAt;

  // ── Health Summary ─────────────────────────────────────────────────
  final double medicationCompliance; // 0.0 to 1.0
  final TrendDirection complianceTrendVsPrevious;
  final int missedMedicationsCount;
  final String? mostProblematicTimeSlot; // "morning", "afternoon", "evening"
  final int symptomsLoggedCount;
  final String? mostFrequentSymptom;

  // ── Fitness Summary ────────────────────────────────────────────────
  final int workoutCount;
  final double totalVolume; // kg
  final TrendDirection volumeTrendVsPrevious;
  final int totalWorkoutDuration; // minutes
  final List<PersonalRecord> newPRs;
  final int currentStreak;

  // ── Cross-Module Highlights ────────────────────────────────────────
  final DateTime? bestDay; // Day with both compliance + workout
  final double healthScore; // 0-100
  final List<Insight> topInsights; // Top 3 insights

  // ── Next Week Suggestions ──────────────────────────────────────────
  final List<String> suggestions;

  WeeklyReport copyWith({
    DateTime? startDate,
    DateTime? endDate,
    DateTime? generatedAt,
    double? medicationCompliance,
    TrendDirection? complianceTrendVsPrevious,
    int? missedMedicationsCount,
    String? mostProblematicTimeSlot,
    int? symptomsLoggedCount,
    String? mostFrequentSymptom,
    int? workoutCount,
    double? totalVolume,
    TrendDirection? volumeTrendVsPrevious,
    int? totalWorkoutDuration,
    List<PersonalRecord>? newPRs,
    int? currentStreak,
    DateTime? bestDay,
    double? healthScore,
    List<Insight>? topInsights,
    List<String>? suggestions,
  }) {
    return WeeklyReport(
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      generatedAt: generatedAt ?? this.generatedAt,
      medicationCompliance: medicationCompliance ?? this.medicationCompliance,
      complianceTrendVsPrevious:
          complianceTrendVsPrevious ?? this.complianceTrendVsPrevious,
      missedMedicationsCount:
          missedMedicationsCount ?? this.missedMedicationsCount,
      mostProblematicTimeSlot:
          mostProblematicTimeSlot ?? this.mostProblematicTimeSlot,
      symptomsLoggedCount: symptomsLoggedCount ?? this.symptomsLoggedCount,
      mostFrequentSymptom: mostFrequentSymptom ?? this.mostFrequentSymptom,
      workoutCount: workoutCount ?? this.workoutCount,
      totalVolume: totalVolume ?? this.totalVolume,
      volumeTrendVsPrevious:
          volumeTrendVsPrevious ?? this.volumeTrendVsPrevious,
      totalWorkoutDuration: totalWorkoutDuration ?? this.totalWorkoutDuration,
      newPRs: newPRs ?? this.newPRs,
      currentStreak: currentStreak ?? this.currentStreak,
      bestDay: bestDay ?? this.bestDay,
      healthScore: healthScore ?? this.healthScore,
      topInsights: topInsights ?? this.topInsights,
      suggestions: suggestions ?? this.suggestions,
    );
  }

  /// Converts the weekly report to JSON for GDPR data export.
  Map<String, dynamic> toJson() {
    return {
      'start_date': startDate.toIso8601String(),
      'end_date': endDate.toIso8601String(),
      'generated_at': generatedAt.toIso8601String(),
      'health_summary': {
        'medication_compliance': medicationCompliance,
        'compliance_trend': complianceTrendVsPrevious.name,
        'missed_medications_count': missedMedicationsCount,
        'most_problematic_time_slot': mostProblematicTimeSlot,
        'symptoms_logged_count': symptomsLoggedCount,
        'most_frequent_symptom': mostFrequentSymptom,
      },
      'fitness_summary': {
        'workout_count': workoutCount,
        'total_volume_kg': totalVolume,
        'volume_trend': volumeTrendVsPrevious.name,
        'total_workout_duration_minutes': totalWorkoutDuration,
        'new_prs': newPRs
            .map(
              (pr) => {
                'exercise_id': pr.exerciseId,
                'weight': pr.weight,
                'reps': pr.reps,
                'estimated_1rm': pr.estimated1RM,
                'achieved_at': pr.achievedAt.toIso8601String(),
              },
            )
            .toList(),
        'current_streak': currentStreak,
      },
      'cross_module_highlights': {
        'best_day': bestDay?.toIso8601String(),
        'health_score': healthScore,
        'top_insights': topInsights
            .map(
              (i) => {
                'title': i.title,
                'message': i.message,
                'category': i.category.name,
                'priority': i.priority.name,
              },
            )
            .toList(),
      },
      'next_week_suggestions': suggestions,
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is WeeklyReport &&
        other.startDate == startDate &&
        other.endDate == endDate &&
        other.generatedAt == generatedAt &&
        other.medicationCompliance == medicationCompliance &&
        other.complianceTrendVsPrevious == complianceTrendVsPrevious &&
        other.missedMedicationsCount == missedMedicationsCount &&
        other.mostProblematicTimeSlot == mostProblematicTimeSlot &&
        other.symptomsLoggedCount == symptomsLoggedCount &&
        other.mostFrequentSymptom == mostFrequentSymptom &&
        other.workoutCount == workoutCount &&
        other.totalVolume == totalVolume &&
        other.volumeTrendVsPrevious == volumeTrendVsPrevious &&
        other.totalWorkoutDuration == totalWorkoutDuration &&
        other.newPRs.length == newPRs.length &&
        other.currentStreak == currentStreak &&
        other.bestDay == bestDay &&
        other.healthScore == healthScore &&
        other.topInsights.length == topInsights.length &&
        other.suggestions.length == suggestions.length;
  }

  @override
  int get hashCode {
    return startDate.hashCode ^
        endDate.hashCode ^
        generatedAt.hashCode ^
        medicationCompliance.hashCode ^
        complianceTrendVsPrevious.hashCode ^
        missedMedicationsCount.hashCode ^
        mostProblematicTimeSlot.hashCode ^
        symptomsLoggedCount.hashCode ^
        mostFrequentSymptom.hashCode ^
        workoutCount.hashCode ^
        totalVolume.hashCode ^
        volumeTrendVsPrevious.hashCode ^
        totalWorkoutDuration.hashCode ^
        newPRs.hashCode ^
        currentStreak.hashCode ^
        bestDay.hashCode ^
        healthScore.hashCode ^
        topInsights.hashCode ^
        suggestions.hashCode;
  }

  @override
  String toString() {
    return 'WeeklyReport(startDate: $startDate, endDate: $endDate, '
        'medicationCompliance: $medicationCompliance, '
        'workoutCount: $workoutCount, healthScore: $healthScore)';
  }
}
