/// VitalSync — Insights Abstract Repository.
///
/// Defines interface for insight repository operations.
library;

/// Abstract repository for generated insights.
///
/// Manages cached insights generated by the InsightEngine.
/// Full method signatures from Prompt 2.3.
abstract class InsightRepository {
  // TODO: Implement in Prompt 2.3 with full method signatures
  // Example methods:
  // Future<List<Insight>> getActive();
  // Future<List<Insight>> getByCategory(InsightCategory category);
  // Future<void> insert(Insight insight);
  // Future<void> markAsRead(int id);
  // Future<void> dismiss(int id);
  // Future<void> clearExpired();
  // Stream<List<Insight>> watchActive();
}
